services:
  web:
    build:
      context: .
    restart: unless-stopped
    env_file: .env
    environment:
      APP_ENV: "production"
      MYSQL_HOST: "db"
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:9.4
    restart: unless-stopped
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mizuki_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   restart: unless-stopped
  #   environment:
  #     PMA_HOST: db
  #   ports:
  #     - "8080:80"

volumes:
  mizuki_data:
